# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_table',
            fields=[
                ('bank_ac_num', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_ifci_code', models.CharField(max_length=30)),
                ('user_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='wallet_table',
            fields=[
                ('mob_num', models.IntegerField(primary_key=True, serialize=False)),
                ('wallet_amnt', models.IntegerField(default=0)),
                ('bank_ac_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SignUp.bank_table')),
            ],
        ),
        migrations.AddField(
            model_name='user_table',
            name='mob_num',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SignUp.wallet_table'),
        ),
    ]
