# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Model',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
            ],
        ),
    ]
