# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='login_model',
            name='pwd',
            field=models.CharField(max_length=20),
        ),
    ]
